name: teledart_app
description: API written on top of teledart, aimed to simplify work with commands and callbacks
version: 1.0.0-dev1
repository: https://github.com/ASGAlex/teledart_app

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  teledart: ^0.2.1
  meta: ^1.7.0
  args: ^2.1.1

dev_dependencies:
  test: ^1.17.10
  pedantic: ^1.11.1
