name: teledart_app
description: API written on top of teledart, aimed to simplify work with commands and callbacks
version: 0.0.2-dev.0
repository: https://github.com/ASGAlex/teledart_app

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  teledart: ^0.1.6
  meta: ^1.3.0
  args: ^1.6.0

dev_dependencies:
  test: ^1.16.0
  pedantic: ^1.10.0
