name: teledart_app
description: API written on top of teledart, aimed to simplify work with commands and callbacks
version: 0.0.1-dev.2
repository: https://github.com/ASGAlex/teledart_app

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  teledart: ^0.1.4
  meta: ^1.3.0
  args: ^1.4.0

dev_dependencies:
  test: ^1.16.0
  pedantic: ^1.10.0
